# kustomize build . >argocd-deploy.yml
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v3.1.6
- namespace.yaml

patches:
- path: argo-cm.yaml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: argocd-lovely-plugin.yaml
  target:
    kind: Deployment
    name: argocd-repo-server
