# kustomize build . >argocd-deploy.yml
#
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- namespace.yml

patches:
- path: argo-cm.yml
  target:
    kind: ConfigMap
    name: argocd-cm
- path: argocd-lovely-plugin.yml
  target:
    kind: Deployment
    name: argocd-repo-server
- path: argocd-vault-replacer.yml
  target:
      kind: Deployment
      name: argocd-repo-server
